/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cuentas` | `/cuentas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/metas` | `/metas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/movimientos` | `/movimientos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/suscripciones` | `/suscripciones`; params?: Router.UnknownInputParams; } | { pathname: `/modals/nueva-categoria`; params?: Router.UnknownInputParams; } | { pathname: `/modals/nueva-cuenta`; params?: Router.UnknownInputParams; } | { pathname: `/modals/nueva-meta`; params?: Router.UnknownInputParams; } | { pathname: `/modals/nueva-suscripcion`; params?: Router.UnknownInputParams; } | { pathname: `/modals/nuevo-movimiento`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cuentas` | `/cuentas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/metas` | `/metas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/movimientos` | `/movimientos`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/suscripciones` | `/suscripciones`; params?: Router.UnknownOutputParams; } | { pathname: `/modals/nueva-categoria`; params?: Router.UnknownOutputParams; } | { pathname: `/modals/nueva-cuenta`; params?: Router.UnknownOutputParams; } | { pathname: `/modals/nueva-meta`; params?: Router.UnknownOutputParams; } | { pathname: `/modals/nueva-suscripcion`; params?: Router.UnknownOutputParams; } | { pathname: `/modals/nuevo-movimiento`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cuentas${`?${string}` | `#${string}` | ''}` | `/cuentas${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/metas${`?${string}` | `#${string}` | ''}` | `/metas${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/movimientos${`?${string}` | `#${string}` | ''}` | `/movimientos${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/suscripciones${`?${string}` | `#${string}` | ''}` | `/suscripciones${`?${string}` | `#${string}` | ''}` | `/modals/nueva-categoria${`?${string}` | `#${string}` | ''}` | `/modals/nueva-cuenta${`?${string}` | `#${string}` | ''}` | `/modals/nueva-meta${`?${string}` | `#${string}` | ''}` | `/modals/nueva-suscripcion${`?${string}` | `#${string}` | ''}` | `/modals/nuevo-movimiento${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cuentas` | `/cuentas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/metas` | `/metas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/movimientos` | `/movimientos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/suscripciones` | `/suscripciones`; params?: Router.UnknownInputParams; } | { pathname: `/modals/nueva-categoria`; params?: Router.UnknownInputParams; } | { pathname: `/modals/nueva-cuenta`; params?: Router.UnknownInputParams; } | { pathname: `/modals/nueva-meta`; params?: Router.UnknownInputParams; } | { pathname: `/modals/nueva-suscripcion`; params?: Router.UnknownInputParams; } | { pathname: `/modals/nuevo-movimiento`; params?: Router.UnknownInputParams; };
    }
  }
}
